#!/bin/bash
#######################################################################
#########  Arkadiusz Borucki
#######################################################################
DBA="aborucki@xxxxxxxx"
ORACLE_SID="A"
 ORACLE_HOME="/Oracle/app/oracle/product/db11g"

c=`ps -elf | grep pmon | grep -v grep | grep -v ASM|grep  pmon| wc -l`
echo $c

if [ $c -eq 0 ];then
echo "Instance down"
return 1
exit
fi
